### ISSUE TITLE
PostCSS nested not fully working

### ISSUE THREAD

**Issue by csheppard** [nuxt-community/tailwindcss-module#227]
### Version
@nuxtjs/tailwindcss: v3.3.4
nuxt: v2.14.11

### Reproduction Link
https://codesandbox.io/s/funny-hugle-1tyt8?file=/pages/index.vue

### Steps to reproduce
I can't append to class names.

I thought maybe I was doing something stupid but the example at [postcss-nested](https://github.com/postcss/postcss-nested) doesnt work either.

```postcss
.test {
  color: red;

  &_working {
    color: green;
  }

  & .nested {
    color: blue;
  }
}
```

### What is Expected?

```css
.test {
  color: red
}
.test_working {
    color: green;
}
.test .nested {
    color: blue;
}
```

### What is actually happening?

```css
.test {
  color: red
}
.test {
&_working {
    color: green;
}
}
.test .nested {
    color: blue;
}
```
