### ISSUE TITLE
Using jit and extractCSS produces mangled CSS

### ISSUE THREAD

**Issue by achaphiv** [nuxt-community/tailwindcss-module#302]
### Version
@nuxtjs/tailwindcss: 4.0.1
nuxt: 2.5.3

### Reproduction Link
https://codesandbox.io/s/zen-lamport-mqs2n?file=/pages/index.vue

### Steps to reproduce
- Fork https://codesandbox.io/s/o4vn5pvp7q
- Add to `nuxt.config.js`
  ```js
  build: {
    extractCSS: true
  }
  ```
- Tailwindcss classes don't work

### What is Expected?
Tailwindcss classes should show up in `app.css`.

The classes somewhat show up. But the names are not correct. I'm not sure if it's mangled, hashed, or obfuscated.

E.G.

```css
._23q1WWN1khtlxe68G3xhJ3 {
	position: static;
}
.JO4Yi0Q5IUg8YnrwyYbmc {
	width: 100%;
}
._2LMPnzdkax2uVcy8XGK8hF {
	--tw-bg-opacity: 1;
	background-color: rgba(239, 68, 68, var(--tw-bg-opacity));
}
```

### What is actually happening?
The introduction of `extractCSS: true` appears to run class names through some sort of transformation?
