### ISSUE TITLE
modern-normalize part uncompressed in style tag

### ISSUE THREAD

**Issue by philipptrenz** [nuxt-community/tailwindcss-module#395]
Hey there,

I'm using nuxt.js in SSR mode and tailwind with JIT compiler. I noticed that tailwind gets embedded via `<style></style>` tag, where the mordernizer part is added uncompressed (including comments), which is followed by the compressed tailwind classes.

My `tailwind.config.js`:

```javascript
module.exports = {
  mode: 'jit',
  theme: { ... },
  variants: { ... },
  plugins: [
    require('@tailwindcss/typography'),
  ],
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js',
      // TypeScript
      'plugins/**/*.ts',
      'nuxt.config.ts'
    ]
  }
}
```

The content of the `style` tag:

```css
/*! tailwindcss v2.2.17 | MIT License | https://tailwindcss.com*/
        /*! modern-normalize v1.1.0 | MIT License | https://github.com/sindresorhus/modern-normalize */

        /*
        Document
        ========
        */

        /**
        Use a better box model (opinionated).
        */
        *, ::before, ::after {
            box-sizing: border-box;
        }/**
        Use a more readable tab size (opinionated).
        */
        html {
            -moz-tab-size: 4;
            -o-tab-size: 4;
            tab-size: 4;
        }/**
        1. Correct the line height in all browsers.
        2. Prevent adjustments of font size after orientation changes in iOS.
        */
        html {
            line-height: 1.15;
            /* 1 */
            -webkit-text-size-adjust: 100%;
            /* 2 */
        }/*
        Sections
        ========
        */

...

hidden] {
              display: none;
            }*, ::before, ::after{--tw-translate-x:0;--tw-translate-y:0;--tw-rotate:0;--tw-skew-x:0;--tw-skew-y:...
```

Thanks a lot!
